apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-pvc
  namespace: nats
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: local-path
