apiVersion: v1
kind: Service
metadata:
  name: nats-nodeport
  namespace: nats
spec:
  type: NodePort
  selector:
    app: nats
  ports:
  - port: 4222
    targetPort: 4222
    nodePort: 30422
    protocol: TCP
    name: client
  - port: 8222
    targetPort: 8222
    nodePort: 30822
    protocol: TCP
    name: monitor

