apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: clickhouse
data:
  config.xml: |
    <clickhouse>
      <logger>
        <level>information</level>
        <console>true</console>
      </logger>
      <http_port>8123</http_port>
      <tcp_port>8200</tcp_port>
      <interserver_http_port>9109</interserver_http_port>
      <listen_host>::</listen_host>
      <mysql_port remove="1"/>
      <postgresql_port remove="1"/>
      <max_connections>4096</max_connections>
      <keep_alive_timeout>3</keep_alive_timeout>
      <max_concurrent_queries>100</max_concurrent_queries>
      <uncompressed_cache_size>8589934592</uncompressed_cache_size>
      <mark_cache_size>5368709120</mark_cache_size>
      <timezone>UTC</timezone>
    </clickhouse>
