apiVersion: v1
kind: ConfigMap
metadata:
  name: scylladb-config
  namespace: scylladb
data:
  scylla.yaml: |
    cluster_name: 'scylla-cluster'
    authenticator: PasswordAuthenticator
    authorizer: CassandraAuthorizer
    num_tokens: 256
    commitlog_sync: periodic
    commitlog_sync_period_in_ms: 10000
    seed_provider:
      - class_name: org.apache.cassandra.locator.SimpleSeedProvider
        parameters:
          - seeds: "scylladb-0.scylladb-headless.scylladb.svc.cluster.local"
    listen_address: auto
    rpc_address: 0.0.0.0
    broadcast_rpc_address: auto
    endpoint_snitch: GossipingPropertyFileSnitch
    native_transport_port: 9042
    api_port: 10000
  cassandra-rackdc.properties: |
    dc=dc1
    rack=rack1
    prefer_local=true
    
