apiVersion: v1
kind: Service
metadata:
  name: scylladb
  namespace: scylladb
spec:
  type: ClusterIP
  selector:
    app: scylladb
  ports:
  - port: 9042
    targetPort: 9042
    protocol: TCP
    name: cql
  - port: 10000
    targetPort: 10000
    protocol: TCP
    name: rest-api

