apiVersion: v1
kind: Service
metadata:
  name: scylladb-nodeport
  namespace: scylladb
spec:
  type: NodePort
  selector:
    app: scylladb
  ports:
  - port: 9042
    targetPort: 9042
    nodePort: 30042
    protocol: TCP
    name: cql

